### ISSUE TITLE
ionic serve works, ionic build - ngc fails

### ISSUE THREAD

**Issue by bowsplinter** [twinssbc/Ionic2-Calendar#12]
Hi I have been following your documentation, works for ionic serve, but ionic emulate fails with this error

```
[17:59:47]  Error: Unexpected value 'NgCalendarModule' imported by the module 'AppModule'
[17:59:47]  ngc failed
[17:59:47]  ionic-app-script task: "build"
[17:59:47]  Error: Error
```

ionic info

```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v5.12.0
```

package.json

```
 "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@ionic/storage": "^1.0.3",
    "ionic-angular": "^2.0.0-rc.0",
    "ionic-native": "^2.0.3",
    "ionic2-calendar": "0.0.9",
    "ionicons": "^3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.36",
    "typescript": "^2.0.3"
  },
```

app.module.ts

```
import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';

import { NgCalendarModule } from 'ionic2-calendar';
import { MapPage } from '../pages/map/map';
import { EventPage } from '../pages/event/event';
import { EventDetailPage } from '../pages/event-detail/event-detail';
import {EventCalendar} from '../pages/event-calendar/event-calendar'
import { InfoPage } from '../pages/info/info';
import { TabsPage } from '../pages/tabs/tabs';

@NgModule({
  declarations: [
    MyApp,
    MapPage,
    EventPage,
    EventDetailPage,
    EventCalendar,
    InfoPage,
    TabsPage
  ],
  imports: [
    NgCalendarModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    MapPage,
    EventPage,
    EventDetailPage,
    EventCalendar,
    InfoPage,
    TabsPage
  ],
  providers: []
})
export class AppModule {}
```

after this I am adding the directive to the html page. 

I understand there are changes after ionic rc, should i be doing things differently?

Any help is appreciated!

**Comment by twinssbc** [comment]
I found a lot of issues were raised when compiling with external libraries.
It seems there's still no final decision that if Ionic build script should be modified or all external libraries should be upgraded.

https://forum.ionicframework.com/t/unexpected-value-ng2completermodule-imported-by-the-module-appmodule/65922/2

Anyway, I will take a look at AOT complication support

**Comment by jayh92** [comment]
Bocong,
Any updates or thoughts on implementing AOT support?
Thank you,
Jay

**Comment by twinssbc** [comment]
@jayh92 I have released a version (0.0.10) using AOT compilation.
There's some issue about importing the ngfactory files, you can check README to learn how to make ionic build command happy.
Feel free to have a try. Thanks.

**Comment by bowsplinter** [comment]
@twinssbc thanks you! I attempted it to implement it with the new instructions but running with errors again when trying to do emulate android

it still works with ionic serve though

```
13    708741   error    EXCEPTION: Cannot convert undefined or null to object
14    708742   error    ORIGINAL STACKTRACE:
15    708743   error    TypeError: Cannot convert undefined or null to object
    at me (http://192.168.64.1:8100/build/main.js:1:21631)
    at http://192.168.64.1:8100/build/main.js:1:22108
    at http://192.168.64.1:8100/build/main.js:1:22343
    at Array.forEach (native)
    at Ee (http://192.168.64.1:8100/build/main.js:1:22310)
    at Function.t.format (http://192.168.64.1:8100/build/main.js:9:29398)
    at t.transform (http://192.168.64.1:8100/build/main.js:9:29729)
    at http://192.168.64.1:8100/build/main.js:1:9214
    at e.detectChangesInternal (http://192.168.64.1:8100/build/main.js:38:16035)
    at e.t.detectChanges (http://192.168.64.1:8100/build/main.js:8:30999)
16    708745   error    Uncaught TypeError: Cannot convert undefined or null to object, http://192.168.64.1:8100/build/polyfills.js, Line: 3
```

using version 0.0.11

**Comment by bowsplinter** [comment]
@twinssbc sorry issue is resolved! Problem was that I had to upgrade dependencies to angular 2.0.1. thank you for your help. will close this issue.
