### ISSUE TITLE
Failed at the ionic2-calendar@0.2.12 build script

### ISSUE THREAD

**Issue by bsuyog16** [twinssbc/Ionic2-Calendar#264]
Hi,
I am using ionic2 calendar in my project (v 0.2.12). While building ionic 2 calendar project with command npm run build --prod I am getting following error as 

> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! ionic2-calendar@0.2.12 build: `rm -rf dist && tsc`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the ionic2-calendar@0.2.12 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

It was working earlier in ionic CLI 3.3.0

I am using :
Ionic -CLI : 3.19.0
npm : 5.6.0
node : 8.9.3

Please help !!

**Comment by bsuyog16** [comment]
Here is my package.json file 
```
{
    "name": "ionic2-calendar",
    "version": "0.2.12",
    "description": "Ionic2 calendar component",
    "keywords": [
        "Ionic2",
        "calendar"
    ],
    "author": {
        "name": "twinsbc"
    },
    "license": "MIT",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/twinssbc/Ionic2-Calendar.git"
    },
    "scripts": {
        "build": "rm -rf dist && tsc",
        "build-prod": "rm -rf aot && node_modules/.bin/ngc -p tsconfig-aot.json && node_modules/.bin/ngc src && mv src/*ngfactory.ts aot && rm -r aot/waste",
        "copy_static_files": "cp -r package.json README.md LICENSE tsconfig.json typings.json typings dist/",
        "copy_static_files_prod": "cp -r package.json README.md LICENSE tsconfig.json typings.json typings aot/",
        "dev": "tsc --watch",
        "postinstall": "typings install"
    },
    "main": "./index.js",
    "dependencies": {},
    "devDependencies": {
        "tslint-ionic-rules": "0.0.5",
        "typescript": "2.0.3",
        "typings": "1.3.1",
        "@angular/common": "2.4.8",
        "@angular/compiler": "2.4.8",
        "@angular/compiler-cli": "2.4.8",
        "@angular/core": "2.4.8",
        "@angular/forms": "2.4.8",
        "@angular/http": "2.4.8",
        "@angular/platform-browser": "2.4.8",
        "@angular/platform-browser-dynamic": "2.4.8",
        "@angular/platform-server": "2.4.8",
        "ionic-angular": "2.3.0",
        "rxjs": "5.0.1",
        "zone.js": "0.7.2",
        "intl": "^1.2.5"
    }
}
```

**Comment by bsuyog16** [comment]
Following are the npm verbose logs 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v8.9.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ionic2-calendar@0.2.12~prebuild: ionic2-calendar@0.2.12
6 info lifecycle ionic2-calendar@0.2.12~build: ionic2-calendar@0.2.12
7 verbose lifecycle ionic2-calendar@0.2.12~build: unsafe-perm in lifecycle true
8 verbose lifecycle ionic2-calendar@0.2.12~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/suyog/kvadrato/modules/Ionic2-Calendar/node_modules/.bin:/home/suyog/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/suyog/Android/Sdk/tools:/home/suyog/Android/Sdk/platform-tools:/home/suyog/software/android-studio/gradle/gradle-3.2/bin
9 verbose lifecycle ionic2-calendar@0.2.12~build: CWD: /home/suyog/kvadrato/modules/Ionic2-Calendar
10 silly lifecycle ionic2-calendar@0.2.12~build: Args: [ '-c', 'rm -rf dist && tsc' ]
11 silly lifecycle ionic2-calendar@0.2.12~build: Returned: code: 2  signal: null
12 info lifecycle ionic2-calendar@0.2.12~build: Failed to exec build script
13 verbose stack Error: ionic2-calendar@0.2.12 build: `rm -rf dist && tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid ionic2-calendar@0.2.12
15 verbose cwd /home/suyog/kvadrato/modules/Ionic2-Calendar
16 verbose Linux 4.4.0-97-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.9.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error ionic2-calendar@0.2.12 build: `rm -rf dist && tsc`
22 error Exit status 2
23 error Failed at the ionic2-calendar@0.2.12 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by twinssbc** [comment]
@bsuyog16 Are you trying to customize the calendar and build it? Or you simply want to use the calendar in your application?
If you want to build the calendar, could you try "npm run build-prod"?
If it fails, you could run each command separately, for example,
```
rm -rf aot
node_modules/.bin/ngc -p tsconfig-aot.json
node_modules/.bin/ngc src
mv src/*ngfactory.ts aot
rm -r aot/waste
```
When you run each command separately, it will print out which command fails and the detailed error message.

**Comment by bsuyog16** [comment]
Hi,

Yes, I have already customised the calendar module and I am using that in my project.
Even If I run "npm run build-prod" it gives me same error. 

If I run this command `node_modules/.bin/ngc -p tsconfig-aot.json` I get error as 

```
Error at node_modules/@types/lodash/index.d.ts:248:13: Cannot redeclare block-scoped variable '_'.
Error at node_modules/@types/lodash/index.d.ts:252:19: Cannot redeclare block-scoped variable '_'.
Error at node_modules/@types/lodash/index.d.ts:4003:40: ',' expected.
Error at node_modules/@types/lodash/index.d.ts:4004:20: ']' expected.
Error at node_modules/@types/lodash/index.d.ts:4004:26: ',' expected.
Error at node_modules/@types/lodash/index.d.ts:4004:27: ',' expected.
Error at node_modules/@types/lodash/index.d.ts:4021:40: ',' expected.
Error at node_modules/@types/lodash/index.d.ts:4022:42: ']' expected.
Error at node_modules/@types/lodash/index.d.ts:4022:48: ',' expected.
Error at node_modules/@types/lodash/index.d.ts:4022:49: ',' expected.
Error at node_modules/@types/lodash/index.d.ts:4039:40: ',' expected.
```


And after running` node_modules/.bin/ngc src` I get error as 
```


Error at /node_modules/@types/lodash/index.d.ts:248:13: Cannot redeclare block-scoped variable '_'.
Error at /node_modules/@types/lodash/index.d.ts:248:16: Cannot find namespace '_'.
Error at /node_modules/@types/lodash/index.d.ts:250:25: Type 'Partial' is not generic.
Error at /node_modules/@types/lodash/index.d.ts:252:19: Cannot redeclare block-scoped variable '_'.
Error at /node_modules/@types/lodash/index.d.ts:3589:12: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:3614:34: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:3639:34: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4001:22: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4003:29: Generic type 'Many' requires 1 type argument(s).
Error at /node_modules/@types/lodash/index.d.ts:4003:40: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4004:12: Generic type 'Array<T>' requires 1 type argument(s).
Error at /node_modules/@types/lodash/index.d.ts:4004:20: ']' expected.
Error at /node_modules/@types/lodash/index.d.ts:4004:26: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4004:27: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4019:22: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4021:29: Generic type 'Many' requires 1 type argument(s).
Error at /node_modules/@types/lodash/index.d.ts:4021:40: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4022:34: Generic type 'Array<T>' requires 1 type argument(s).
Error at /node_modules/@types/lodash/index.d.ts:4022:42: ']' expected.
Error at /node_modules/@types/lodash/index.d.ts:4022:48: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4022:49: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4037:22: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4039:29: Generic type 'Many' requires 1 type argument(s).
Error at /node_modules/@types/lodash/index.d.ts:4039:40: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4040:34: Generic type 'Array<T>' requires 1 type argument(s).
Error at /node_modules/@types/lodash/index.d.ts:4040:42: ']' expected.
Error at /node_modules/@types/lodash/index.d.ts:4040:48: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4040:49: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4081:27: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4099:27: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4125:27: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4172:24: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4211:29: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4243:25: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4261:25: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4287:25: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4345:26: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4345:46: ']' expected.
Error at /node_modules/@types/lodash/index.d.ts:4345:52: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4345:52: Duplicate identifier 'T'.
Error at /node_modules/@types/lodash/index.d.ts:4345:53: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4347:24: Generic type 'ObjectIteratorTypeGuard' requires 3 type argument(s).
Error at /node_modules/@types/lodash/index.d.ts:4353:26: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4356:12: Generic type 'Array<T>' requires 1 type argument(s).
Error at /node_modules/@types/lodash/index.d.ts:4356:20: ']' expected.
Error at /node_modules/@types/lodash/index.d.ts:4356:26: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4356:27: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4387:26: Cannot find name 'object'.
Error at /node_modules/@types/lodash/index.d.ts:4387:46: ']' expected.
Error at /node_modules/@types/lodash/index.d.ts:4387:52: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4387:52: Duplicate identifier 'T'.
Error at /node_modules/@types/lodash/index.d.ts:4387:53: ',' expected.
Error at /node_modules/@types/lodash/index.d.ts:4389:24: Generic type 'ObjectIterator
```

For rest commands I am not facing any error.

**Comment by twinssbc** [comment]
@bsuyog16 You mean you directly add the calendar source code in your project and run "npm run build-prod"?
If you want to modify the source code. You should fork this repository in a separate project, modify the code, build it, then only added the generated files in aot folder into your app project.
When you run "npm install" in your app project, you probably will install the calendar in the node_modules folder, then you could use the generated files to replace them.
