### ISSUE TITLE
Cannot find module "ionic2-calendar"

### ISSUE THREAD

**Issue by Breshit** [twinssbc/Ionic2-Calendar#270]
Hello
I have installed all things as was necessary, but this error still persists:

`Error: Cannot find module "ionic2-calendar"
   at 339 (http://localhost:8100/build/main.js:154:1)
   at __webpack_require__ (http://localhost:8100/build/vendor.js:55:12)
   at 315 (http://localhost:8100/build/main.js:134:22)
   at __webpack_require__ (http://localhost:8100/build/vendor.js:55:12)
   at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:14)
   at Global code (http://localhost:8100/build/main.js:1:1)`

Any help, please?

**Comment by twinssbc** [comment]
@Breshit Could you check if ionic2-calendar exists in your node_modules directory? How do you import the module in your app module file?

**Comment by Breshit** [comment]
I checked.
Before giving this bug the calendar worked, even without existing in the directory node_modules.
My solution was to directly install Ionic2-calendar 0.4.x, because I had version 0.3.x.
But thanks for the help. :)
