### ISSUE TITLE
Object doesn't support property or method 'getTime'

### ISSUE THREAD

**Issue by shCampos** [twinssbc/Ionic2-Calendar#272]
Hello @twinssbc I'm getting this error on execute ionic serve. Have you any suggestion about what it can be?

Runtime Error
`Object doesn't support property or method 'getTime'`

Stack
`TypeError: Object doesn't support property or method 'getTime'
   at MonthViewComponent.prototype.onDataLoaded (http://localhost:8100/build/vendor.js:172248:43)
   at MonthViewComponent.prototype.ngOnChanges (http://localhost:8100/build/vendor.js:172100:13)
   at checkAndUpdateDirectiveDynamic (http://localhost:8100/build/vendor.js:12473:9)
   at checkAndUpdateNodeDynamic (http://localhost:8100/build/vendor.js:13973:13)
   at checkAndUpdateNode (http://localhost:8100/build/vendor.js:13897:9)
   at debugCheckAndUpdateNode (http://localhost:8100/build/vendor.js:14766:5)
   at debugCheckDirectivesFn (http://localhost:8100/build/vendor.js:14707:13)
   at Anonymous function (Function code:186:5)
   at debugUpdateDirectives (http://localhost:8100/build/vendor.js:14692:5)
   at checkAndUpdateView (http://localhost:8100/build/vendor.js:13861:5)`

I'm using Ionic 3.9 and Angular 5.

**Comment by twinssbc** [comment]
@Breshit How to you specify your startTime and endTime of the event? I suspect you are using a String instead of a Date object?

**Comment by robertrobertlow** [comment]
Must we definitely need end time?

**Comment by twinssbc** [comment]
@robertrobertlow If you don't need endTime, how could you till how long does the event take?

**Comment by robertrobertlow** [comment]
This is why I do not need endTime, Since my intention was to work scheduling calendar. Which endTime is unknown. Is there any walkabout? Thankyou.

**Comment by robertrobertlow** [comment]
I would just like to pluck and put into the correct timing spot

**Comment by twinssbc** [comment]
@robertrobertlow Could you please create a separate issue? Your question is not relevant to this issue.
