### ISSUE TITLE
I get Cannot find module "intl" error

### ISSUE THREAD

**Issue by RezaRahmati** [twinssbc/Ionic2-Calendar#38]
Hi

I tried to use the ionic2-Calendar but I get the below error when I try to run the app by ionic serve

Cannot find module "intl"
Error: Cannot find module "intl"
    at Object.<anonymous> (http://localhost:8100/build/main.js:117496:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:117876:75)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:94583:74)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:133104:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10

p.s I installed intl by npm install -g intl and still error

Would you please help me out

**Comment by twinssbc** [comment]
@RezaRahmati Could you check if Intl is successfully installed in your npm repository?
What if you just only install it locally?

**Comment by RezaRahmati** [comment]
@twinssbc Hi I added it by `npm install intl --save-dev` and issue is resolved, it might be a good idea to update installation docs too.
