### ISSUE TITLE
Runtime Error Cannot find module "intl"

### ISSUE THREAD

**Issue by hgoraya** [twinssbc/Ionic2-Calendar#46]
i tried to integrate date picker bu ti am getting this error:

Runtime Error
Cannot find module "intl"

stacktrace:
Error: Cannot find module "intl"
    at Object.<anonymous> (http://localhost:8100/build/main.js:108974:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:109354:75)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:90056:74)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:123658:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10

Any help please

**Comment by alexandretok** [comment]
Try issuing this command:

`npm install intl@1.2.5 --save`

**Comment by amorriscode** [comment]
@alexandretok I simply ran `npm install intl` and it worked for me.

**Comment by yurik94** [comment]
Same error, this should be added to the wiki!

**Comment by twinssbc** [comment]
I have added this issue into Common Questions in README.

**Comment by gazialankus** [comment]
So, everyone who clones our repository has to do npm install --save? Also for ionic2-calendar here: https://github.com/twinssbc/Ionic2-Calendar#usage

Is there a way this could be made so that someone can clone my repository that uses ionic2-calendar and does not have to issue manual "npm install --save" commands?

**Comment by twinssbc** [comment]
@gazialankus I don't quite understand your requirement.
In theory, when you start a new project, you will specify some dependency in package.json and you always need to run "npm install" to install the dependencies so that you can reference them.
But you don't need some one run "npm install ionic2-calendar --save" explicitly if you already added ionic2-calendar dependency in your package.json.
